name: flutter_tests
description: "Example of test types."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # https://pub.dev/packages/alchemist
  alchemist: 0.12.1
  # https://pub.dev/packages/flutter_lints
  flutter_lints: 5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true